### ISSUE TITLE
Potential blocking while loops, please add a timeout

### ISSUE THREAD

**Issue by PatrickDekker98** [R2D2-2019/I2C_library#11]
https://github.com/R2D2-2019/I2C_library/blob/e1ab9c87fec39a53a64c97dcc9a8b7fb6d185095/code/src/i2c_bus.cpp#L121 
https://github.com/R2D2-2019/I2C_library/blob/e1ab9c87fec39a53a64c97dcc9a8b7fb6d185095/code/src/i2c_bus.cpp#L131 

These lines contain while loops that could be eternally blocking. The solution could be a time-out .

**Comment by florianhumblot** [comment]
Unless this is actually a problem that engineers experience with their hardware I don't see the added value of giving the engineers more cases to handle.
These loops shouldn't handle forever unless there's a hardware issue.

**Comment by florianhumblot** [comment]
fixed #12
