### ISSUE TITLE
Method for setting clock cycle

### ISSUE THREAD

**Issue by Kaaserne** [R2D2-2019/I2C_library#15]
Because the MLX90640 chip can read EEPROM data only with a maximum speed of 400kHz, and this only has to be done during startup, I wondered if there could be a function to set the clockspeed. After the EEPROM calibration data has been read I want to increase the speed to 1MHz.

**Comment by florianhumblot** [comment]
@MarcDirven I've created a new branch (feature-speed_selection_runtime), and added a function that will let you change the speed at runtime.

Please test this version and report if you find any issues.

**Comment by Kaaserne** [comment]
I've just tested it and happy to say that it works. Thanks!
