### ISSUE TITLE
Repeated starts

### ISSUE THREAD

**Issue by itzandroidtab** [R2D2-2019/I2C_library#8]
For our sensor we need a repeated start. (The MLX90615 and MLX90640).

This means that the bus doesnt send a stop after writing some bytes first.

For the MLX90615 sensor we need to send 1 byte of data before the read and with the MLX90640 we need to send 2 bytes of data before the read.

**Comment by florianhumblot** [comment]
I won't be able to look into this issue until this weekend, if it's urgent, I suggest you make a pull request, otherwise I'll do my best to have it working by the end of the weekend.

Should you start working on this, please let me know so I don't start it in parallel.

**Comment by florianhumblot** [comment]
After looking into repeated starts for a bit, are you sure you don't actually need access to the `internal address` instead of repeated starts? Those are potentially also easier to implement, might be able to have it done by tomorrow evening.

**Comment by itzandroidtab** [comment]
Using the internal address gives the repeated start. I dont think there is another way to get the repeated starts on the arduino due.

**Comment by florianhumblot** [comment]
Currently fixed in release branch and there's a pull request (#10) waiting to be merged to master.
